# Generated by Django 5.2.3 on 2025-09-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('moisture', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('ph', models.FloatField()),
                ('nitrogen', models.FloatField()),
                ('phosphorous', models.FloatField()),
                ('potassium', models.FloatField()),
                ('carbon', models.FloatField()),
                ('soil', models.IntegerField(choices=[(0, 'Sandy'), (1, 'Loamy'), (2, 'Black'), (3, 'Red'), (4, 'Clayey')])),
                ('crop', models.IntegerField(choices=[(0, 'Maize'), (1, 'Sugarcane'), (2, 'Cotton'), (3, 'Tobacco'), (4, 'Paddy'), (5, 'Barley'), (6, 'Wheat'), (7, 'Millets'), (8, 'Oil seeds'), (9, 'Pulses')])),
                ('recommended_fertilizer', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
