# Generated by Django 5.2.3 on 2025-09-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('moisture', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('ph', models.FloatField()),
                ('nitrogen', models.FloatField()),
                ('phosphorous', models.FloatField()),
                ('potassium', models.FloatField()),
                ('carbon', models.FloatField()),
                ('soil', models.IntegerField(choices=[(0, 'Acidic_Soil'), (1, 'Alkaline_Soil'), (2, 'Loamy_Soil'), (3, 'Neutral_Soil'), (4, 'Peaty_Soil')])),
                ('crop', models.IntegerField(choices=[(0, 'Rice'), (1, 'Moth Beans'), (2, 'Pomegranate'), (3, 'Papaya'), (4, 'Orange'), (5, 'Muskmelon'), (6, 'Mango'), (7, 'Apple'), (8, 'Grapes'), (9, 'Banana'), (10, 'Chickpea'), (11, 'Pigeon Peas'), (12, 'Adzuki Beans'), (13, 'Black gram'), (14, 'Coconut'), (15, 'Kidney Beans'), (16, 'Wheat'), (17, 'Tobacco'), (18, 'Sugarcane'), (19, 'Rubber'), (20, 'Peas'), (21, 'Ground Nut'), (22, 'Cotton'), (23, 'Coffee'), (24, 'Jute'), (25, 'Lentil'), (26, 'Maize'), (27, 'Millet'), (28, 'Tea'), (29, 'Mung Bean'), (30, 'Watermelon')])),
                ('predicted_fertilizer', models.CharField(blank=True, choices=[('Balanced NPK Fertilizer', 'Balanced NPK Fertilizer'), ('Compost', 'Compost'), ('DAP', 'DAP'), ('General Purpose Fertilizer', 'General Purpose Fertilizer'), ('Gypsum', 'Gypsum'), ('Lime', 'Lime'), ('Muriate of Potash', 'Muriate of Potash'), ('Organic Fertilizer', 'Organic Fertilizer'), ('Urea', 'Urea'), ('Water Retaining Fertilizer', 'Water Retaining Fertilizer')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FertilizerModel',
        ),
    ]
